version: '3'
services:
  practice-dnn:
    restart: always
    build: .
    container_name: 'practice-dnn'
    working_dir: '/root/'
    tty: true
    volumes:
      - type: bind
        source: .
        target: /root/practice-dnn
